# Generated by Django 2.2.6 on 2019-10-10 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                ('user_id', models.CharField(default='b7f7be6a-42ca-4da4-8519-3c236bf5422a', max_length=64, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.CharField(default='8ed70e9a-fcd7-4308-a6ed-700329e6ae7c', max_length=64, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.CharField(default='4b8f8a9b-b122-49d3-9db4-37ad4d5691b7', max_length=64, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_from', to='chat_api.ChatUser')),
                ('sent_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_to', to='chat_api.ChatUser')),
            ],
        ),
    ]
