# Generated by Django 2.2.6 on 2019-10-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='user_id',
            field=models.CharField(default='a574d764-cc50-4699-a8d8-7c599a941023', max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='user_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(default='c081eafe-d90b-4a7d-99d6-8d858e9827ef', max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_id',
            field=models.CharField(default='e53830ab-657c-44db-b7fe-acbe243b143b', max_length=64, primary_key=True, serialize=False),
        ),
    ]
