# Generated by Django 2.2.6 on 2019-10-10 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0002_auto_20191010_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='n_message',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chat_api.Message'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='user_id',
            field=models.CharField(default='390be1e1-dbe2-4740-969a-4401e5543a60', max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.CharField(default='23584900-c496-4ef9-92a9-c7c68cf27b0a', max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_id',
            field=models.CharField(default='423da051-af85-4ec0-976d-ca2c2d0379c0', max_length=64, primary_key=True, serialize=False),
        ),
    ]
